###
POST  http://localhost:4000/api/book
Content-Type: application/json

{
 "titel": "Java",
 "author": "Pedro",
 "read": true
}

###
GET http://localhost:4000/api/book

###
GET http://localhost:4000/api/book

###
PUT  http://localhost:4000/api/book

###
DELETE  http://localhost:4000/api/book